# This rule is not used by the project amazonq-golang-restfulapi-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.aws.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: amazonq-golang-restfulapi-operator
    app.kubernetes.io/managed-by: kustomize
  name: restapi-editor-role
rules:
- apiGroups:
  - apps.aws.com
  resources:
  - restapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.aws.com
  resources:
  - restapis/status
  verbs:
  - get
