# This rule is not used by the project amazonq-golang-restfulapi-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.aws.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: amazonq-golang-restfulapi-operator
    app.kubernetes.io/managed-by: kustomize
  name: restapi-admin-role
rules:
- apiGroups:
  - apps.aws.com
  resources:
  - restapis
  verbs:
  - '*'
- apiGroups:
  - apps.aws.com
  resources:
  - restapis/status
  verbs:
  - get
